hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 15
deployment:
  desiredReplicas: 2
  imageVersion: v1
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  # nodePort: 30011
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:339712874850:targetgroup/expense-dev/12fd98a4ff730489