kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: frontend
  namespace: expense
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: nginx
        image: joindevops/frontend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: NodePort
  selector:
    app: frontend
    tier: expense
    project: expense
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30011