kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
medatada:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: backend
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
spec:
  replicas: {{ .Values.deployment.desiredReplicas }}
  selector:
    matchLabels:
      app: backend
      tier: api
      project: expense
  template:
    medatada:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:{{ .Values.deployment.imageVersion }}
        envFrom:
        - configMapRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
---
kind: ConfigMap
apiVersion: v1
medatada:
  name: backend
  namespace: expense
data:
  DB_HOST: {{ .Values.configMap.DB_HOST }}